POST http://localhost:3000/api/v1/recipe/create HTTP/1.1
content-type: application/json

{
  "name": "Strawberry pie",
  "description": "Delicious orange pie with high sugar dose. First: cut onions in tiny slices. Second: Mix orange and onion. Third: let your pet taste it. Fourth: enjoy it.",
  "author": "Peter",
  "avg_rating": 5,
  "img": "assets/images/orange-pie.png",
  "is_public": false,
  "ingredients": [
    {
      "_id": "1111111",
      "qty": 300
    },
    {
      "_id": "2222222",
      "qty": 100
    }
  ],
  "meal_type": "Lunch",
  "country": "France",
  "cooking_time": 60,
  "difficulty": "hard",
  "views": 195,
  "food_type": "medieterranean",
  "comments": [
    {
      "title": "Esperaba más",
      "comment": "Nisi officia fugiat id nulla laboris ex. Sit laboris culpa occaecat occaecat aliquip dolor non excepteur reprehenderit.",
      "id_user": "63cb0277ee58877e63e36fcc"
    },
    {
      "title": "Buenisimo",
      "comment": "Nisi officia fugiat id nulla laboris ex. Sit laboris culpa occaecat occaecat aliquip dolor non excepteur reprehenderit.",        
      "id_user": "63cb0277ee58877e63e36fcc"
    }
  ]
}